name: workflow_ci_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==3.1.0
      - scikit-learn==1.6.1
      - pandas==2.2.3
      - matplotlib==3.10.1
      - seaborn==0.13.2
