name: MLflow CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train_model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name: Check Python version
      run: python --version

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        environment-file: MLProject/conda.yaml
        activate-environment: mlflow-env

    - name: Verify Conda Environment and MLflow
      run: |
        conda env list
        conda run -n mlflow-env mlflow --version

    - name: Run MLflow Project
      run: |
        cd MLProject
        conda run -n mlflow-env mlflow run . --no-conda

    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: MLProject/mlruns/
